services:
  mysql:
    image: mysql
    ports:
     - 23306:3306
    volumes:
     - mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    ports:
      - 8101:80
volumes:
  mysql:



